
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import * as THREE from 'three'
import { useFrame, useThree } from '@react-three/fiber'

// Ground bounds (matching the town area based on city positions + padding)
const GROUND_BOUNDS = { minX: -20, maxX: 11, minZ: -6, maxZ: 3 }

function isOverGround(x, z) {
  return x >= GROUND_BOUNDS.minX && x <= GROUND_BOUNDS.maxX &&
         z >= GROUND_BOUNDS.minZ && z <= GROUND_BOUNDS.maxZ
}

export default function Car({ path, onReachEnd, driveMode = false, keysRef, cityPositions, ...props }) {
  const { nodes, materials } = useGLTF('/models/car.glb')
  const characterRef = useRef()
  const tRef = useRef(0)
  const directionRef = useRef(1)
  const speed = 0.01

  // Drive mode state
  const velocityRef = useRef(new THREE.Vector3())
  const rotationRef = useRef(0)
  const gravityVelRef = useRef(0)
  const spawnPos = useRef(new THREE.Vector3(8, 1.55, -1.5))
  const { camera } = useThree()

  useFrame((_, delta) => {
    if (!characterRef.current) return

    if (driveMode && keysRef?.current) {
      // Free drive mode — keyboard/joystick controls
      const keys = keysRef.current
      const driveSpeed = 8
      const turnSpeed = 2.5
      const friction = 0.92

      // Turning
      if (keys.left) rotationRef.current += turnSpeed * delta
      if (keys.right) rotationRef.current -= turnSpeed * delta

      // Forward direction — car model faces -X
      const forward = new THREE.Vector3(
        -Math.cos(rotationRef.current),
        0,
        Math.sin(rotationRef.current)
      )

      if (keys.forward) velocityRef.current.addScaledVector(forward, driveSpeed * delta)
      if (keys.backward) velocityRef.current.addScaledVector(forward, -driveSpeed * delta * 0.6)

      // Apply friction (horizontal only)
      velocityRef.current.x *= friction
      velocityRef.current.z *= friction

      // Update horizontal position
      characterRef.current.position.x += velocityRef.current.x * delta * 10
      characterRef.current.position.z += velocityRef.current.z * delta * 10

      // Check if car is over the ground platform
      const overGround = isOverGround(
        characterRef.current.position.x,
        characterRef.current.position.z
      )

      const groundLevel = 1.55

      if (overGround && characterRef.current.position.y <= groundLevel) {
        // On solid ground
        gravityVelRef.current = 0
        characterRef.current.position.y = groundLevel
      } else {
        // In the air — apply gravity (either drove off edge or jumping)
        gravityVelRef.current -= 20 * delta
        characterRef.current.position.y += gravityVelRef.current * delta
      }

      // Collision with city buildings (simple AABB push-back)
      if (cityPositions) {
        const carX = characterRef.current.position.x
        const carZ = characterRef.current.position.z
        const carRadius = 0.8

        for (const pos of Object.values(cityPositions)) {
          const bx = pos[0], bz = pos[2]
          const buildingRadius = 1.2
          const dx = carX - bx
          const dz = carZ - bz
          const dist = Math.sqrt(dx * dx + dz * dz)
          const minDist = carRadius + buildingRadius

          if (dist < minDist && dist > 0) {
            // Push car out
            const overlap = minDist - dist
            const nx = dx / dist
            const nz = dz / dist
            characterRef.current.position.x += nx * overlap
            characterRef.current.position.z += nz * overlap
            // Kill velocity in collision direction
            const dot = velocityRef.current.x * nx + velocityRef.current.z * nz
            if (dot < 0) {
              velocityRef.current.x -= nx * dot * 1.2
              velocityRef.current.z -= nz * dot * 1.2
            }
          }
        }
      }

      // Respawn if fell too far
      if (characterRef.current.position.y < -15) {
        characterRef.current.position.copy(spawnPos.current)
        velocityRef.current.set(0, 0, 0)
        gravityVelRef.current = 0
        rotationRef.current = 0
      }

      // Apply rotation
      characterRef.current.rotation.y = rotationRef.current

      // Camera: tight behind the car
      const camBehind = new THREE.Vector3(
        Math.cos(rotationRef.current) * 1.5,
        1.0,
        -Math.sin(rotationRef.current) * 1.5
      )
      const targetCamPos = characterRef.current.position.clone().add(camBehind)
      camera.position.lerp(targetCamPos, 0.12)
      camera.lookAt(characterRef.current.position)

    } else if (path && tRef.current < 1) {
      // Path-following mode (original behavior)
      let nextT = tRef.current + directionRef.current * speed

      if (nextT >= 1) {
        nextT = 1
        directionRef.current = -1
        if (onReachEnd) onReachEnd()
      } else if (nextT <= 0) {
        nextT = 0
        directionRef.current = 1
      }

      const point = path.getPointAt(nextT)
      characterRef.current.position.copy(point)

      const tangent = path.getTangentAt(Math.min(nextT, 1)).normalize()
      tangent.y = 0
      tangent.normalize()

      const forward = new THREE.Vector3(-1, 0, 0)
      const quaternion = new THREE.Quaternion().setFromUnitVectors(forward, tangent)
      characterRef.current.quaternion.slerp(quaternion, 0.2)

      tRef.current = nextT
    }
  })

  // Reset position when path changes (only in path mode)
  useEffect(() => {
    if (path && !driveMode) {
      tRef.current = 0
      directionRef.current = 1
    }
  }, [path, driveMode])

  // Reset drive state when entering drive mode
  useEffect(() => {
    if (driveMode && characterRef.current) {
      velocityRef.current.set(0, 0, 0)
      rotationRef.current = characterRef.current.rotation.y
    }
  }, [driveMode])

  // Helper for Toon + Outline
  const Part = ({ geometry, material, ...rest }) => (
    <mesh
      castShadow
      receiveShadow
      geometry={geometry}
      {...rest}
    >
      <meshToonMaterial color={material ? material.color : "white"} />
      <Outlines thickness={0.9} color="black" />
      {rest.children}
    </mesh>
  )

  return (
    <group scale={0.3} ref={characterRef} {...props} dispose={null}>
      <group rotateY={Math.PI / 2} scale={[0.52, 0.288, 0.52]}>
        <Part geometry={nodes.Cube001_1.geometry} material={materials['Material.003']} />
        <Part geometry={nodes.Cube001_2.geometry} material={materials['Material.003']} />
        <Part geometry={nodes.Cube001_3.geometry} material={materials['Material.001']} />
        <Part geometry={nodes.Cube001_4.geometry} material={materials['Material.001']} />
        <Part geometry={nodes.Cube001_5.geometry} material={materials['Material.001']} />
        <Part geometry={nodes.Cube001_6.geometry} material={materials['Material.004']} />
        <Part geometry={nodes.Cube001_7.geometry} material={materials['Material.001']} />

        <group position={[0, 0, 0.017]}>
          <Part geometry={nodes.Cube002_1.geometry} material={materials['Material.003']} />
          <Part geometry={nodes.Cube002_2.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-0.006, 0, 0.402]} rotation={[Math.PI, 0, Math.PI]}>
          <Part geometry={nodes.Cube002_1.geometry} material={materials['Material.003']} />
          <Part geometry={nodes.Cube002_2.geometry} material={materials['Material.001']} />
        </group>
        <group position={[0, 0, 0.402]} rotation={[Math.PI, 0, Math.PI]}>
          <Part geometry={nodes.Cube003_1.geometry} material={materials['Material.003']} />
          <Part geometry={nodes.Cube003_2.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-0.006, 0, 0.017]}>
          <Part geometry={nodes.Cube003_1.geometry} material={materials['Material.003']} />
          <Part geometry={nodes.Cube003_2.geometry} material={materials['Material.001']} />
        </group>

        <Part geometry={nodes.Cube005.geometry} material={materials['Material.001']} />
        <Part geometry={nodes.Cube006.geometry} material={materials['Material.001']} position={[0, -0.498, 0]} />
        <Part geometry={nodes.Cube007.geometry} material={materials['Material.001']} position={[-0.943, -0.227, 0.397]} rotation={[Math.PI, 0, Math.PI]} />

        {/* Wheels */}
        <group position={[1.292, -2.752, -0.873]} rotation={[Math.PI / 2, 0, 0]} scale={[0.434, 0.099, 0.785]}>
          <Part geometry={nodes.Cylinder_1.geometry} material={materials['Material.001']} />
          <Part geometry={nodes.Cylinder_2.geometry} material={materials['Material.002']} />
        </group>
        <group position={[1.292, -2.752, 1.276]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.434, 0.099, 0.785]}>
          <Part geometry={nodes.Cylinder_1.geometry} material={materials['Material.001']} />
          <Part geometry={nodes.Cylinder_2.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-2.132, -2.752, -0.873]} rotation={[Math.PI / 2, 0, 0]} scale={[0.434, 0.099, 0.785]}>
          <Part geometry={nodes.Cylinder_1.geometry} material={materials['Material.001']} />
          <Part geometry={nodes.Cylinder_2.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-2.132, -2.752, 1.276]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.434, 0.099, 0.785]}>
          <Part geometry={nodes.Cylinder_1.geometry} material={materials['Material.001']} />
          <Part geometry={nodes.Cylinder_2.geometry} material={materials['Material.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/car.glb')
