/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Outlines } from '@react-three/drei'

export default function Ground(props) {
  const { nodes, materials } = useGLTF('/models/ground.glb')

  // Helper for Toon + Outline
  const Part = ({ geometry, material, ...rest }) => (
    <mesh
      castShadow
      receiveShadow
      geometry={geometry}
      {...rest}
    >
      <meshToonMaterial color={material ? material.color : "white"} />
    </mesh>
  )

  return (
    <group {...props} dispose={null}>
      <group position={[4.278, 0.3, 0.25]} scale={[4.044, 1, 0.506]}>
        <Part geometry={nodes.Plane001.geometry} material={materials['Material.010']} />
        <Part geometry={nodes.Plane001_1.geometry} material={materials['Material.011']} />
        <Part geometry={nodes.Plane001_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/ground.glb')