/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'

export default function Tank(props) {
  const { nodes, materials } = useGLTF('/models/tank.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.425, 0.613, 3.639]} scale={[0.221, 0.479, 0.221]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
        >
          <meshToonMaterial color={materials['Material.007'].color} />
          <Outlines thickness={0.9} color="black" />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
        >
          <meshToonMaterial color={materials['Material.008'].color} />
          <Outlines thickness={0.02} color="black" />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_2.geometry}
        >
          <meshToonMaterial color={materials['Material.009'].color} />
          <Outlines thickness={0.02} color="black" />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/tank.glb')
