/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'

export default function Tree(props) {
  const { nodes, materials } = useGLTF('/models/tree.glb')

  const TreePart = ({ geometry, material, ...rest }) => (
    <mesh
      castShadow
      receiveShadow
      geometry={geometry}
      {...rest}
    >
      <meshToonMaterial color={material.color} />
      <Outlines thickness={0.9} color="black" />
      {rest.children}
    </mesh>
  )

  return (
    <group {...props} dispose={null}>
      <TreePart
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.013']}
        scale={0.051}
      >
        <TreePart geometry={nodes.Sphere002.geometry} material={materials['Material.012']} position={[1.629, 12.088, -0.057]} scale={2.516} />
        <TreePart geometry={nodes.Sphere003.geometry} material={materials['Material.012']} position={[-1.829, 11.896, -0.057]} scale={2.516} />
        <TreePart geometry={nodes.Sphere004.geometry} material={materials['Material.012']} position={[0.886, 13.454, 0.796]} scale={2.516} />
        <TreePart geometry={nodes.Sphere005.geometry} material={materials['Material.012']} position={[-1.827, 14.586, -0.802]} scale={1.627} />
        <TreePart geometry={nodes.Sphere006.geometry} material={materials['Material.012']} position={[5.074, 11.708, -0.057]} scale={1.734} />
        <TreePart geometry={nodes.Sphere007.geometry} material={materials['Material.012']} position={[2.241, 14.189, 1.14]} scale={1.63} />
        <TreePart geometry={nodes.Sphere008.geometry} material={materials['Material.012']} position={[1.199, 13.384, -2.244]} scale={1.855} />
        <TreePart geometry={nodes.Sphere009.geometry} material={materials['Material.012']} position={[2.484, 8.709, -2.578]} scale={2.012} />
        <TreePart geometry={nodes.Sphere010.geometry} material={materials['Material.012']} position={[3.166, 11.3, 2.994]} scale={1.6} />
        <TreePart geometry={nodes.Sphere011.geometry} material={materials['Material.012']} position={[-1.253, 10.935, -2.939]} scale={2.099} />
        <TreePart geometry={nodes.Sphere012.geometry} material={materials['Material.012']} position={[-1.445, 10.935, 3.402]} scale={2.023} />
        <TreePart geometry={nodes.Sphere013.geometry} material={materials['Material.012']} position={[5.856, 8.875, 0.327]} scale={1.714} />
        <TreePart geometry={nodes.Sphere014.geometry} material={materials['Material.012']} position={[0.634, 16.184, 0.309]} scale={1.252} />
        <TreePart geometry={nodes.Sphere015.geometry} material={materials['Material.012']} position={[-4.327, 11.127, 0.327]} scale={2.221} />
        <TreePart geometry={nodes.Sphere016.geometry} material={materials['Material.012']} position={[-3.798, 8.746, 0.327]} scale={2.055} />
        <TreePart geometry={nodes.Sphere017.geometry} material={materials['Material.012']} position={[3.477, 9.011, 0.327]} scale={2.055} />
        <TreePart geometry={nodes.Sphere018.geometry} material={materials['Material.012']} position={[3.477, 8.879, 3.105]} scale={2.055} />
        <TreePart geometry={nodes.Sphere019.geometry} material={materials['Material.012']} position={[0.435, 9.408, -2.847]} scale={2.055} />
        <TreePart geometry={nodes.Sphere020.geometry} material={materials['Material.012']} position={[-3.534, 9.408, 1.782]} scale={2.055} />
        <TreePart geometry={nodes.Sphere021.geometry} material={materials['Material.012']} position={[-3.666, 9.408, -1.921]} scale={2.055} />
        <TreePart geometry={nodes.Sphere022.geometry} material={materials['Material.012']} position={[1.361, 9.408, 4.031]} scale={2.055} />
        <TreePart geometry={nodes.Sphere023.geometry} material={materials['Material.012']} position={[2.812, 11.635, -3.007]} scale={1.173} />
      </TreePart>
    </group>
  )
}

useGLTF.preload('/models/tree.glb')
