/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'

export default function WaterTank(props) {
  const { nodes, materials } = useGLTF('/models/water tank.glb')

  const Part = ({ geometry, material, ...rest }) => (
    <mesh
      castShadow
      receiveShadow
      geometry={geometry}
      {...rest}
    >
      <meshToonMaterial color={material ? material.color : "white"} />
      <Outlines thickness={0.9} color="black" />
      {rest.children}
    </mesh>
  )

  return (
    <group {...props} dispose={null}>
      <group position={[-0.001, 0.904, 3.351]} scale={[0.165, 0.712, 0.165]}>
        <Part geometry={nodes.Cylinder_1.geometry} material={materials['Material.004']} />
        <Part geometry={nodes.Cylinder_2.geometry} material={materials['Material.005']} />
        <Part geometry={nodes.Cylinder_3.geometry} material={materials['Material.006']} />
      </group>

      <Part geometry={nodes.NurbsPath.geometry} material={materials['Material.006']} position={[0.033, 1.421, 3.189]} rotation={[0, Math.PI / 2, 0]} scale={0.779} />
      <Part geometry={nodes.NurbsPath001.geometry} material={materials['Material.006']} position={[-0.038, 1.421, 3.189]} rotation={[0, Math.PI / 2, 0]} scale={0.779} />
      <Part geometry={nodes.NurbsPath005.geometry} material={materials['Material.006']} position={[-0.004, 1.168, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath006.geometry} material={materials['Material.006']} position={[-0.004, 1.084, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath007.geometry} material={materials['Material.006']} position={[-0.004, 1, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath002.geometry} material={materials['Material.006']} position={[-0.004, 1.421, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath003.geometry} material={materials['Material.006']} position={[-0.004, 1.337, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath004.geometry} material={materials['Material.006']} position={[-0.004, 1.253, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath008.geometry} material={materials['Material.006']} position={[-0.004, 0.916, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath009.geometry} material={materials['Material.006']} position={[-0.004, 0.831, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath010.geometry} material={materials['Material.006']} position={[-0.004, 0.747, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath011.geometry} material={materials['Material.006']} position={[-0.004, 0.663, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath012.geometry} material={materials['Material.006']} position={[-0.004, 0.579, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath013.geometry} material={materials['Material.006']} position={[-0.004, 0.495, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath014.geometry} material={materials['Material.006']} position={[-0.004, 0.41, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath015.geometry} material={materials['Material.006']} position={[-0.004, 0.326, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
      <Part geometry={nodes.NurbsPath016.geometry} material={materials['Material.006']} position={[-0.004, 0.242, 3.092]} rotation={[Math.PI / 2, 0, -2.256]} scale={0.779} />
    </group>
  )
}

useGLTF.preload('/models/water tank.glb')